config/routes.rb
Rails.application.routes.draw do
  get 'feed/index'
  devise_for :users

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index] do
    member do
      post 'follow'
      delete 'unfollow'
    end
  end

  root 'posts#index'
  get 'feed', to: 'feed#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true,
            length: { maximum: 80 },
            uniqueness: { scope: :user_id, message: "You already have a post with this title" }

  validates :body, presence: true,
            length: { in: 8..1000 }
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

  validates :follower_id, uniqueness: { scope: :followee_id }
  validate :not_self_subscription

  private

  def not_self_subscription
    errors.add(:base, "Cannot subscribe to yourself") if follower_id == followee_id
  end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, foreign_key: :follower_id, dependent: :destroy
  has_many :followees, through: :subscriptions, source: :followee
  has_many :reverse_subscriptions, foreign_key: :followee_id, class_name: 'Subscription', dependent: :destroy
  has_many :followers, through: :reverse_subscriptions, source: :follower

  def following?(other_user)
    followees.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params.merge(user: current_user))

    flash[:alert] = 'Error adding comment.' unless @comment.save
    redirect_to @post
  end


  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.user == current_user
      @comment.destroy
      redirect_to @post, notice: 'Comment was successfully deleted.'
    else
      redirect_to @post, alert: 'You are not authorized to delete this comment.'
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!

  POSTS_PER_PAGE = 20

  def index
    @page = current_page
    @posts = fetch_posts
    @total_pages = calculate_total_pages
  end

  private

  def current_page
    [params[:page].to_i, 1].max
  end

  def fetch_posts
    filtered_posts
      .order(created_at: :desc)
      .includes(:user, :comments)
      .distinct
      .offset((@page - 1) * POSTS_PER_PAGE)
      .limit(POSTS_PER_PAGE)
  end

  def calculate_total_pages
    total_posts = filtered_posts.distinct.count
    (total_posts.to_f / POSTS_PER_PAGE).ceil
  end

  def filtered_posts
    Post.left_joins(user: :followers)
        .where("subscriptions.follower_id = :user_id OR posts.user_id = :user_id", user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :ensure_owner, only: [:edit, :update, :destroy]

  POSTS_PER_PAGE = 20

  def index
    if user_signed_in?
      @page = [params[:page].to_i, 1].max
      @posts = current_user.posts
                           .order(created_at: :desc)
                           .offset((@page - 1) * POSTS_PER_PAGE)
                           .limit(POSTS_PER_PAGE)
      @total_pages = (current_user.posts.count.to_f / POSTS_PER_PAGE).ceil
    else
      redirect_to new_user_session_path
    end
  end

  def show
    if authorized_to_view_post?
      render :show
    else
      redirect_to new_user_session_path, alert: "You need to sign in or follow the user to view this post."
    end
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorized_to_view_post?
    @post.user == current_user || (user_signed_in? && current_user.following?(@post.user))
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def ensure_owner
    unless @post && @post.user == current_user
      redirect_to posts_path, alert: 'You are not authorized to perform this action.'
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.subscriptions.create(followee: @user)
    redirect_to @user, notice: 'You are now following this user.'
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.subscriptions.find_by(followee: @user).destroy
    redirect_to @user, notice: 'You have unfollowed this user.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def show
    @user = User.find(params[:id])
    @posts = visible_posts_for(@user)
  end

  def index
    @users = User.where.not(id: current_user.id)
  end

  def follow
    @user = User.find(params[:id])
    current_user.followees << @user
    redirect_to @user, notice: 'You are now following this user.'
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followees.delete(@user)
    redirect_to @user, notice: 'You have unfollowed this user.'
  end

  private

  def visible_posts_for(user)
    if user_signed_in?
      return user.posts.order(created_at: :desc) if user == current_user || current_user.following?(user)
    end
    user.posts.none
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.comment{id: "comment-#{comment.id}", style: "margin-left: #{comment.parent_id ? '20px' : '0'}"}
  %p= comment.body
  %small
    Commented by #{comment.user.email} at #{comment.created_at.strftime('%B %d, %Y %H:%M')}
  - if user_signed_in? && current_user == comment.user
    = link_to 'Delete', post_comment_path(comment.post, comment), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }
  - if user_signed_in?
    = link_to 'Reply', '#', class: 'reply-link', data: { comment_id: comment.id }

  .reply-form{id: "reply-form-#{comment.id}", style: 'display: none;'}
    = form_with(model: [comment.post, Comment.new], remote: true) do |form|
      = form.hidden_field :parent_id, value: comment.id
      = form.text_area :body, rows: 3
      = form.submit 'Reply'

  .replies{id: "replies-#{comment.id}"}
    = render comment.replies

app/views/comments/_form.html.haml
= form_with(model: [post, comment], local: true) do |form|
  - if comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - comment.errors.full_messages.each do |message|
          %li= message

  .form-group
    = form.label :body
    = form.text_area :body, rows: 3

  .actions
    = form.submit 'Add Comment'

app/views/feed/index.html.haml
%h1 Your Feed

- if @posts.any?
  - @posts.each do |post|
    .post
      %h2= link_to post.title, post_path(post)
      %p= truncate(post.body, length: 200)
      %small
        Posted by #{link_to post.user.email, user_path(post.user)} at #{post.created_at.strftime('%B %d, %Y %H:%M')}
      %p
        = pluralize(post.comments.count, 'comment')
- else
  %p You're not following anyone yet, or the people you follow haven't posted anything.
  = link_to 'Find users to follow', users_path

= render 'shared/pagination', page: @page, total_pages: @total_pages

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Social Network
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  %body
    %header
      %nav
        = link_to 'Home', root_path
        = link_to 'Feed', feed_path
        = link_to 'Users', users_path
        - if user_signed_in?
          = link_to 'Profile', user_path(current_user)
          = link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete }
        - else
          = link_to 'Sign up', new_user_registration_path
          = link_to 'Log in', new_user_session_path

    - flash.each do |_name, msg|
      - if msg.is_a?(String)
        %p.notice= msg

    = yield

app/views/posts/_form.html.haml
= form_with(model: post, local: true) do |form|
  - if post.errors.any?
    #error_explanation
      %h2= "#{pluralize(post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - post.errors.full_messages.each do |message|
          %li= message

  .form-group
    = form.label :title
    = form.text_field :title

  .form-group
    = form.label :body
    = form.text_area :body, rows: 5

  .actions
    = form.submit

%hr
= link_to 'Back to Posts', posts_path

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form', post: @post

app/views/posts/index.html.haml
%h1 Your Posts

= link_to 'New Post', new_post_path, class: 'btn btn-primary'

.posts
  - if @posts.any?
    - @posts.each do |post|
      .post
        %h2= link_to post.title, post_path(post)
        %p= truncate(post.body, length: 200)
        %small
          Posted at #{post.created_at.strftime('%B %d, %Y %H:%M')}
        = link_to 'Edit', edit_post_path(post)
        = link_to 'Delete', post_path(post), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }
  - else
    %p You haven't created any posts yet.

= render 'shared/pagination', page: @page, total_pages: @total_pages

app/views/posts/new.html.haml
%h1 New Post

= render 'form', post: @post

app/views/posts/show.html.haml
%h1= @post.title
%p= @post.body
%small
  Posted by #{@post.user.email} at #{@post.created_at.strftime('%B %d, %Y %H:%M')}

- if user_signed_in? && current_user == @post.user
  = link_to 'Edit', edit_post_path(@post)
  = link_to 'Delete', post_path(@post), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

%h2 Comments
= render @post.comments.where(parent_id: nil)

%h3 Add a comment:
= form_with(model: [@post, Comment.new], local: true) do |form|
  = form.text_area :body, rows: 3
  = form.submit 'Add Comment'

%hr
= link_to 'Back to Posts', posts_path

app/views/shared/_pagination.html.haml
- if total_pages && total_pages > 1
  .pagination
    - if page && page > 1
      = link_to 'Previous', feed_path(page: page - 1)
    - if page && total_pages && page < total_pages
      = link_to 'Next', feed_path(page: page + 1)
    %p
      Page #{page} of #{total_pages}

app/views/users/index.html.haml
%h1 Users

%ul
  - @users.each do |user|
    %li
      = link_to user.email, user_path(user)
      - if user_signed_in? && current_user != user
        - if current_user.followees.include?(user)
          = button_to 'Unfollow', unfollow_user_path(user), method: :delete
        - else
          = button_to 'Follow', follow_user_path(user), method: :post

app/views/users/show.html.haml
%h1= @user.email

- if user_signed_in? && current_user != @user
  - if current_user.followees.include?(@user)
    = button_to 'Unfollow', unfollow_user_path(@user), method: :delete
  - else
    = button_to 'Follow', follow_user_path(@user), method: :post

%h2 Followers
%ul
  - @user.followers.each do |follower|
    %li= link_to follower.email, user_path(follower)

%h2 Following
%ul
  - @user.followees.each do |followee|
    %li= link_to followee.email, user_path(followee)

%h2 Posts
- @posts.each do |post|
  .post
    %h3= link_to post.title, post
    %p= truncate(post.body, length: 100)
    %small Posted at #{post.created_at}